"""PyPI package detector — parses three manifest formats.

A Python package can declare its name in any of:

- ``pyproject.toml`` ``[project].name`` (PEP 621, modern)
- ``pyproject.toml`` ``[tool.poetry].name`` (Poetry, also modern)
- ``setup.cfg`` ``[metadata].name`` (declarative, older)
- ``setup.py`` literal ``setup(name='...')`` call (oldest, common)

Real projects often have several at once (e.g. ``setup.py`` plus
``setup.cfg``). To avoid double-counting we walk for any of these
files, group results by parent directory, and prefer one source per
directory in the order above — the modern formats first because
they're authoritative when present.

A ``setup.py`` whose name field is computed dynamically (read from
``__init__.py``, generated by a helper, etc.) is not parseable by
regex and gets logged-and-skipped. Such packages slip through this
detector; the matcher will then log them as unmatched targets,
which is exactly the right behaviour — we'd rather under-report
than misattribute.
"""

from __future__ import annotations

import configparser
import re
import tomllib
from typing import TYPE_CHECKING

from harvester.manifest_discovery._logger import logger
from harvester.manifest_discovery.base import (
    should_skip_directory,
)
from harvester.manifest_discovery.discovery_types import (
    DiscoveredPackage,
)

if TYPE_CHECKING:
    from collections.abc import Iterator
    from pathlib import Path


# Sources ordered by authority. When a directory has more than one,
# we use the first hit from this list and ignore the rest.
_MANIFEST_PRIORITY: tuple[str, ...] = (
    "pyproject.toml",
    "setup.cfg",
    "setup.py",
)

# Captures ``name="foo"`` or ``name='foo'`` inside a ``setup(...)``
# call. Doesn't try to validate the surrounding call — many real
# setup.py files split the call across multiple lines, embed
# computations, or wrap ``setup`` in a custom function. The regex
# matches the common case (literal string assignment to ``name``)
# and lets the rare metaprogrammatic case fall through as unmatched.
_SETUP_PY_NAME = re.compile(
    r"""(?:^|[\s,(])name\s*=\s*['"]([A-Za-z0-9][A-Za-z0-9._-]*)['"]""",
)


class PypiManifestDetector:
    """Discovers PyPI packages via pyproject.toml / setup.cfg / setup.py."""

    ecosystem = "PYPI"

    def discover(self, repo_dir: Path) -> Iterator[DiscoveredPackage]:
        """Yield at most one record per directory containing a manifest.

        When a directory contains both ``pyproject.toml`` and
        ``setup.py``, we honour the modern format and skip the
        legacy one — the names are nearly always identical in
        practice, and reporting both would inflate the package count.
        """
        for package_dir, manifest_path in self._iter_manifest_dirs(repo_dir):
            name = self._read_name(manifest_path)
            if name is None:
                continue
            relative_path = package_dir.relative_to(repo_dir).as_posix()
            yield DiscoveredPackage(
                name=name,
                relative_path=relative_path,
                manifest_file=manifest_path.name,
            )

    @staticmethod
    def _iter_manifest_dirs(repo_dir: Path) -> Iterator[tuple[Path, Path]]:
        """Walk and yield ``(package_dir, chosen_manifest)`` per directory.

        For each visited directory, picks the first manifest from
        ``_MANIFEST_PRIORITY`` that exists. Directories with no
        Python manifest produce nothing.
        """
        stack: list[Path] = [repo_dir]
        while stack:
            current = stack.pop()
            try:
                entries = list(current.iterdir())
            except (OSError, PermissionError):
                continue
            file_names = {entry.name for entry in entries if entry.is_file()}
            for manifest_name in _MANIFEST_PRIORITY:
                if manifest_name in file_names:
                    yield current, current / manifest_name
                    break
            for entry in entries:
                if entry.is_dir() and not should_skip_directory(entry.name):
                    stack.append(entry)

    @classmethod
    def _read_name(cls, manifest_path: Path) -> str | None:
        """Dispatch by filename, returning ``None`` on any parse failure."""
        try:
            if manifest_path.name == "pyproject.toml":
                return cls._read_pyproject_name(manifest_path)
            if manifest_path.name == "setup.cfg":
                return cls._read_setup_cfg_name(manifest_path)
            if manifest_path.name == "setup.py":
                return cls._read_setup_py_name(manifest_path)
        except OSError as error:
            logger.debug(
                "pypi manifest unreadable, skipping",
                manifest=str(manifest_path),
                error=str(error),
            )
        return None

    @staticmethod
    def _read_pyproject_name(manifest_path: Path) -> str | None:
        """Read PEP 621 ``[project].name`` or Poetry ``[tool.poetry].name``."""
        try:
            with manifest_path.open("rb") as fh:
                data = tomllib.load(fh)
        except tomllib.TOMLDecodeError as error:
            logger.debug(
                "pyproject.toml malformed, skipping",
                manifest=str(manifest_path),
                error=str(error),
            )
            return None
        project = data.get("project")
        if isinstance(project, dict):
            name = project.get("name")
            if isinstance(name, str) and name:
                return name
        poetry = data.get("tool", {}).get("poetry") if isinstance(data, dict) else None
        if isinstance(poetry, dict):
            name = poetry.get("name")
            if isinstance(name, str) and name:
                return name
        return None

    @staticmethod
    def _read_setup_cfg_name(manifest_path: Path) -> str | None:
        """Read ``[metadata].name`` from a declarative setup.cfg."""
        parser = configparser.ConfigParser()
        try:
            parser.read(manifest_path, encoding="utf-8")
        except configparser.Error as error:
            logger.debug(
                "setup.cfg malformed, skipping",
                manifest=str(manifest_path),
                error=str(error),
            )
            return None
        if not parser.has_option("metadata", "name"):
            return None
        name = parser.get("metadata", "name").strip()
        return name or None

    @staticmethod
    def _read_setup_py_name(manifest_path: Path) -> str | None:
        """Best-effort regex on the ``setup(name='...')`` literal."""
        content = manifest_path.read_text(encoding="utf-8", errors="replace")
        match = _SETUP_PY_NAME.search(content)
        return match.group(1) if match else None
